substitutions:
  devicename: esphome1

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename} Fallback Hotspot
    password: !secret ap_pass

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

web_server:

status_led:
  pin: 2

i2c:
  id: bus_a
  sda: 21
  scl: 22
  scan: True

uart:
  - id: bus_b
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
  - id: bus_c
    rx_pin: 3
    baud_rate: 9600

# output:
#   - platform: ledc
#     id: rtttl_out
#     pin: 32

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
          send_first_at: 1
  - platform: wifi_signal
    name: WiFi Signal Sensor
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
          send_first_at: 1
  - platform: sht3xd
    temperature:
      name: Temperature
      id: sht31d_temp
    humidity:
      name: Humidity
      id: sht31d_hum
    i2c_id: bus_a
    address: 0x44
    update_interval: 1s
  - platform: bmp280
    temperature:
      # name: BMP280 Temperature
      id: bmp280_temp
      oversampling: 16x
    pressure:
      name: Pressure
    address: 0x76
    update_interval: 1s
  - platform: sgp30
    eco2:
      # name: eCO2
      id: sgp30_eco2
      accuracy_decimals: 0
    tvoc:
      name: TVOC
      accuracy_decimals: 0
    address: 0x58
    update_interval: 1s
  - platform: bh1750
    name: Illuminance
    address: 0x23
    measurement_duration: 254
    update_interval: 1s
  - platform: mhz19
    co2:
      name: CO2
    temperature:
      # name: MH-Z19 Temperature
      id: mhz19_temp
    uart_id: bus_b
    update_interval: 1s
    automatic_baseline_calibration: false
  - platform: pmsx003
    type: PMSX003
    uart_id: bus_c
    pm_1_0:
      name: PM1
      device_class: pm1
    pm_2_5:
      name: PM2.5
      device_class: pm25
    pm_10_0:
      name: PM10
      device_class: pm10
  - platform: adc
    id: adc_1
    pin: 34
    attenuation: 11db
    accuracy_decimals: 3
    update_interval: 1s
  - platform: template
    name: Combustible Gas
    accuracy_decimals: 0
    update_interval: 1s
    state_class: measurement
    unit_of_measurement: ppm
    icon: mdi:fire
    lambda: return pow(((356.72892938145003 * (1.3 - 0.005 * id(sht31d_hum).state) * (1 + 0.01 * id(sht31d_temp).state)) / (5 * 1.0 / id(adc_1).state - 1.0)), 1.5831598494221564);
  - platform: adc
    id: adc_2
    pin: 35
    attenuation: 6db
    accuracy_decimals: 3
    update_interval: 1s
  - platform: template
    name: Noxious Gas
    accuracy_decimals: 0
    update_interval: 1s
    state_class: measurement
    unit_of_measurement: ppm
    icon: mdi:bottle-tonic-skull
    lambda: return pow(((77.8709342319244 * (1.3 - 0.005 * id(sht31d_hum).state) * (1 + 0.01 * id(sht31d_temp).state)) / (5 * 1.0 / id(adc_2).state - 1.0)), 2.3389732367593274);

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 4
    num_leds: 4
    rgb_order: GRB
    name: FastLED
    effects:
      - addressable_rainbow:
          speed: 10
          width: 10

# rtttl:
#   output: rtttl_out
